service: lambda-sensui

plugins:
  - serverless-offline
  - serverless-kms-secrets

provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
  environment:
      SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}

custom:
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}

functions:
  fund:
    description: Fund handler
    handler: src/api_handler.fund
    timeout: 30
    events:
     - http:
         path: v1/fund #Legacy
         method: post
     - http:
         path: fund
         method: post
  relay:
    description: Relay handler
    handler: src/api_handler.relay
    timeout: 30
    events:
     - http:
         path: v2/relay #Legacy
         method: post
     - http:
         path: relay
         method: post
  checkPending:
    handler: src/api_handler.checkPending
    description: uPort check if pending tx are mined
    events:
     - http:
         path: checkPending
         method: post
  checkBalances:
    handler: src/jobs_handler.checkBalances
    description: uPort check for balances on all address used and report if low funds
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true
  fixNonces:
    handler: src/script_handler.fixNonces
    description: uPort fix for blockchain nonces against database stored nonce
